# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    admin.course:
        class: App\Admin\CourseAdmin
        arguments: [~, App\Entity\Courses, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'College Programs', label: Courses }

    admin.subjects:
        class: App\Admin\SubjectsAdmin
        arguments: [~, App\Entity\Subjects, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'College Programs', label: Subjects }

    admin.teachers:
        class: App\Admin\TeacherAdmin
        arguments: [~, App\Entity\Teacher, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Faculty', label: Teachers }

    admin.semester:
        class: App\Admin\SemesterAdmin
        arguments: [~, App\Entity\Semester, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'College Programs', label: Semester }

    admin.chapters:
        class: App\Admin\ChapterAdmin
        arguments: [~, App\Entity\Chapters, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'College Programs', label: Chapters }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
